# Generated by Django 4.1.1 on 2023-03-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Emp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_name", models.CharField(blank=True, max_length=255, null=True)),
                ("emp_id", models.IntegerField()),
                ("emp_sal", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_name", models.CharField(max_length=200)),
                ("stu_no", models.CharField(max_length=100)),
                ("stu_roll", models.IntegerField()),
            ],
        ),
    ]
